<p>使用 <code>finally</code> 块中的 <code>return</code>、<code>break</code>、<code>throw</code> 和 <code>continue</code>
  覆盖类似来自挂起的 <code>try</code> 和 <code>catch</code> 块的语句。
</p>
<p>当跳转语句<code>break</code>、<code>continue</code>、<code>return</code> 和 <code>throw</code>会强制控制流时，
  此规则会引发问题留下一个 <code>finally</code> 块。</p>
<h2>不合规示例</h2>
<pre>
function foo() {
    try {
        return 1; // 我们期望返回 1
    } catch(err) {
        return 2; // 在错误的情况下返回 2
    } finally {
        return 3; // 不合规: 3 在 1 或 2 之后返回，这真是匪夷所思
    }
}
</pre>
<h2>合规示例</h2>
<pre>
function foo() {
    try {
        return 1; // 我们期望返回 1
    } catch(err) {
        return 2; // 在错误的情况下返回 2
    }
}
</pre>

